create table if not exists public.notifications (
  notification_id integer generated by default as identity primary key,
  company_id integer not null references public.user_company(company_id),
  user_id integer not null references public.user_info(user_id),
  rfq_id integer not null references public.rfq_analysis(rfq_id),
  event_type text not null,
  report_type text not null,
  title text not null,
  message text not null,
  is_read boolean not null default false,
  read_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint notifications_read_state_check
    check ((is_read = false and read_at is null) or is_read = true),
  constraint notifications_final_report_unique
    unique (company_id, user_id, rfq_id, event_type, report_type)
);

create index if not exists notifications_tenant_unread_created_idx
  on public.notifications (company_id, user_id, is_read, created_at desc);

create index if not exists notifications_tenant_rfq_created_idx
  on public.notifications (company_id, user_id, rfq_id, created_at desc);
